export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SINGLE_PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const SINGLE_PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_FAIL = "PRODUCT_FAIL";
export const SINGLE_CLEAR_ERROR = "CLEAR_ERROR";
